// <auto-generated />
using System;
using ECommerce.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221015084427_AddedProductandCategorySeedAgain")]
    partial class AddedProductandCategorySeedAgain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c405483e-b35c-4c4e-9e7e-387b5527f0b7"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 8, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7167), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Default"
                        },
                        new
                        {
                            Id = new Guid("7a61cf49-d11a-494d-95ca-c649ed215773"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 8, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7173), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("d6dcf59a-0cf7-4c22-aff5-38cd0223aca0"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 8, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7191), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Vegetable"
                        },
                        new
                        {
                            Id = new Guid("0b42eb8c-a7fd-46aa-a88c-8d656b016115"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 8, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7199), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Seasonal Food"
                        },
                        new
                        {
                            Id = new Guid("136e59e2-2046-460f-ad0e-60b75f3748c9"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 8, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7206), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Phone"
                        },
                        new
                        {
                            Id = new Guid("7d0059e3-816c-44e1-8e36-adb7c74e1c7c"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 8, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7210), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Cloths"
                        },
                        new
                        {
                            Id = new Guid("7e2c655f-5e84-48c7-bda1-ad178a7be899"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 8, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7214), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Gadgets"
                        });
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f23b443b-2185-4dd7-9952-8a91185e5244"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 8, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7396), new TimeSpan(0, 0, 0, 0, 0)),
                            ProductId = new Guid("7410bdfd-c2f1-4f29-b8b1-1321810cc9a9"),
                            Quantity = 23
                        },
                        new
                        {
                            Id = new Guid("97081fb9-f963-4125-aee3-ae7deaecb0ec"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 8, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7403), new TimeSpan(0, 0, 0, 0, 0)),
                            ProductId = new Guid("72a73a5f-1930-49e3-b924-d72b59c050a2"),
                            Quantity = 25
                        });
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b08643fd-487f-401c-97bb-6117531abc7a"),
                            ConcurrencyStamp = "638014418660556793",
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 8, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(6832), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("DeleteQueue")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7410bdfd-c2f1-4f29-b8b1-1321810cc9a9"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7264), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Apex Shoes",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7282), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("17a7dff9-34fd-44e6-98c2-aa9dd60392ef"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7291), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Mango",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7293), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0564dc12-ca23-4508-8f53-8a4c5aefe1a9"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7301), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "JackFruit",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7303), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0c7dbebf-c240-405b-9883-1606ec29da00"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7313), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Apple",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7315), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7f6a2181-c381-4e6f-9c14-d9fc2c85b4f2"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7321), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Banana",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7323), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("c8fe1651-fd04-4c52-a3c1-634ad6d0e413"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7333), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Black Berry",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7336), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("9d9791cd-737c-4de8-bdfd-acf51a1dbb83"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7343), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Green Apple",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7346), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("da35a95d-6862-45e1-8f10-6c0a5e1200d0"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7352), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Date",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7355), new TimeSpan(0, 6, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ProductDelete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TriggeredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ProductDeletes");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("168528cc-7ba4-452d-b4bf-d8032b3c2ef7"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7437), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("7410bdfd-c2f1-4f29-b8b1-1321810cc9a9"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7441), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\NoImageFound.png"
                        },
                        new
                        {
                            Id = new Guid("9b545b2c-7e36-41ac-b39a-052cd61c8d4c"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7452), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("72a73a5f-1930-49e3-b924-d72b59c050a2"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 14, 44, 26, 55, DateTimeKind.Unspecified).AddTicks(7454), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\NoImageFound.png"
                        });
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ReviewImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImages");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Inventory", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Product", "Product")
                        .WithOne("ProductInventory")
                        .HasForeignKey("ECommerce.Infrastructure.Entities.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.RoleClaim", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Membership.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserClaim", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Membership.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserLogin", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Membership.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserRole", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Membership.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Infrastructure.Entities.Membership.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserToken", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Membership.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ProductCategory", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Infrastructure.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ProductImage", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Review", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ReviewImage", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Review", "Review")
                        .WithMany("ReviewImages")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Product", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductInventory");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Review", b =>
                {
                    b.Navigation("ReviewImages");
                });
#pragma warning restore 612, 618
        }
    }
}
