// <auto-generated />
using System;
using ECommerce.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221015095344_AddedProductImageSeedAgain")]
    partial class AddedProductImageSeedAgain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c405483e-b35c-4c4e-9e7e-387b5527f0b7"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 9, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(7860), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Default"
                        },
                        new
                        {
                            Id = new Guid("7a61cf49-d11a-494d-95ca-c649ed215773"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 9, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(7866), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("d6dcf59a-0cf7-4c22-aff5-38cd0223aca0"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 9, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(7869), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Vegetable"
                        },
                        new
                        {
                            Id = new Guid("0b42eb8c-a7fd-46aa-a88c-8d656b016115"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 9, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(7873), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Seasonal Food"
                        },
                        new
                        {
                            Id = new Guid("136e59e2-2046-460f-ad0e-60b75f3748c9"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 9, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(7876), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Phone"
                        },
                        new
                        {
                            Id = new Guid("7d0059e3-816c-44e1-8e36-adb7c74e1c7c"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 9, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(7960), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Cloths"
                        },
                        new
                        {
                            Id = new Guid("7e2c655f-5e84-48c7-bda1-ad178a7be899"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 9, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(7963), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Category Description Example....",
                            ImageUrl = "Files\\NoImageFound.png",
                            Name = "Gadgets"
                        });
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f23b443b-2185-4dd7-9952-8a91185e5244"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 9, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8093), new TimeSpan(0, 0, 0, 0, 0)),
                            ProductId = new Guid("7410bdfd-c2f1-4f29-b8b1-1321810cc9a9"),
                            Quantity = 23
                        },
                        new
                        {
                            Id = new Guid("97081fb9-f963-4125-aee3-ae7deaecb0ec"),
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 9, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8098), new TimeSpan(0, 0, 0, 0, 0)),
                            ProductId = new Guid("72a73a5f-1930-49e3-b924-d72b59c050a2"),
                            Quantity = 25
                        });
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b08643fd-487f-401c-97bb-6117531abc7a"),
                            ConcurrencyStamp = "638014460237097579",
                            CreatedBy = "Admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 9, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(7608), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("DeleteQueue")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7410bdfd-c2f1-4f29-b8b1-1321810cc9a9"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(7999), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Apex Shoes",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8010), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("17a7dff9-34fd-44e6-98c2-aa9dd60392ef"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8016), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Mango",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8018), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0564dc12-ca23-4508-8f53-8a4c5aefe1a9"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8023), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "JackFruit",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8024), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("0c7dbebf-c240-405b-9883-1606ec29da00"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8029), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Apple",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8030), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7f6a2181-c381-4e6f-9c14-d9fc2c85b4f2"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8035), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Banana",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8036), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("c8fe1651-fd04-4c52-a3c1-634ad6d0e413"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8042), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Black Berry",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8043), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("3384cc0b-0030-4972-9454-159d47149677"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8047), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Blue Berry",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8048), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("c272683a-c8d9-4e9d-b876-16f1e6f0d557"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8052), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Green Berry",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8053), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("9d9791cd-737c-4de8-bdfd-acf51a1dbb83"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8057), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Green Apple",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8058), new TimeSpan(0, 6, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("da35a95d-6862-45e1-8f10-6c0a5e1200d0"),
                            ActiveStatus = true,
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8062), new TimeSpan(0, 6, 0, 0, 0)),
                            DeleteQueue = false,
                            Description = "This is the best product...........",
                            DiscountedPrice = 3000m,
                            Featured = false,
                            Name = "Date",
                            UnitPrice = 2500m,
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8063), new TimeSpan(0, 6, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("7f6a2181-c381-4e6f-9c14-d9fc2c85b4f2"),
                            CategoryId = new Guid("7a61cf49-d11a-494d-95ca-c649ed215773")
                        },
                        new
                        {
                            ProductId = new Guid("7f6a2181-c381-4e6f-9c14-d9fc2c85b4f2"),
                            CategoryId = new Guid("d6dcf59a-0cf7-4c22-aff5-38cd0223aca0")
                        },
                        new
                        {
                            ProductId = new Guid("7f6a2181-c381-4e6f-9c14-d9fc2c85b4f2"),
                            CategoryId = new Guid("0b42eb8c-a7fd-46aa-a88c-8d656b016115")
                        },
                        new
                        {
                            ProductId = new Guid("17a7dff9-34fd-44e6-98c2-aa9dd60392ef"),
                            CategoryId = new Guid("7a61cf49-d11a-494d-95ca-c649ed215773")
                        },
                        new
                        {
                            ProductId = new Guid("0564dc12-ca23-4508-8f53-8a4c5aefe1a9"),
                            CategoryId = new Guid("7a61cf49-d11a-494d-95ca-c649ed215773")
                        },
                        new
                        {
                            ProductId = new Guid("0c7dbebf-c240-405b-9883-1606ec29da00"),
                            CategoryId = new Guid("7a61cf49-d11a-494d-95ca-c649ed215773")
                        });
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ProductDelete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TriggeredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ProductDeletes");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("168528cc-7ba4-452d-b4bf-d8032b3c2ef7"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8129), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("17a7dff9-34fd-44e6-98c2-aa9dd60392ef"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8131), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\NoImageFound.png"
                        },
                        new
                        {
                            Id = new Guid("9b545b2c-7e36-41ac-b39a-052cd61c8d4c"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8137), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("17a7dff9-34fd-44e6-98c2-aa9dd60392ef"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8139), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\NoImageFound.png"
                        },
                        new
                        {
                            Id = new Guid("35eb699e-2178-4aa9-aa35-9da2f042f5aa"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8143), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("17a7dff9-34fd-44e6-98c2-aa9dd60392ef"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8145), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\NoImageFound.png"
                        },
                        new
                        {
                            Id = new Guid("0221e486-e1fb-4f70-bb50-b527d1f28aa9"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8149), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("0564dc12-ca23-4508-8f53-8a4c5aefe1a9"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8150), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMax.jpg"
                        },
                        new
                        {
                            Id = new Guid("a0fc5bd0-c61b-4245-912c-592f364119ee"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8154), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("0564dc12-ca23-4508-8f53-8a4c5aefe1a9"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8155), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMax.jpg"
                        },
                        new
                        {
                            Id = new Guid("cd51ede2-86ed-4be8-90a7-a793533180a9"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8159), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("0564dc12-ca23-4508-8f53-8a4c5aefe1a9"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8161), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMax.jpg"
                        },
                        new
                        {
                            Id = new Guid("48ecb090-d6e6-456e-ae46-3bac53c6940d"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8164), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("0c7dbebf-c240-405b-9883-1606ec29da00"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8166), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMax2.jpg"
                        },
                        new
                        {
                            Id = new Guid("39002937-6e1b-4aae-8c44-48f4f6110b4b"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8170), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("0c7dbebf-c240-405b-9883-1606ec29da00"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8171), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMax2.jpg"
                        },
                        new
                        {
                            Id = new Guid("e8378dea-aa5f-4687-ad57-59c7beb7dd78"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8175), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("0c7dbebf-c240-405b-9883-1606ec29da00"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8176), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMax2.jpg"
                        },
                        new
                        {
                            Id = new Guid("4ff8ed54-c165-40e9-ab72-41badce8bf96"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8180), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("7f6a2181-c381-4e6f-9c14-d9fc2c85b4f2"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8181), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMax3.jpg"
                        },
                        new
                        {
                            Id = new Guid("cf9c16f2-f231-4333-8f03-80eb2e0ad668"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8188), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("7f6a2181-c381-4e6f-9c14-d9fc2c85b4f2"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8190), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMax3.jpg"
                        },
                        new
                        {
                            Id = new Guid("4c78c682-3db8-475e-adbc-acf6ef43cef7"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8195), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("7f6a2181-c381-4e6f-9c14-d9fc2c85b4f2"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8197), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMax3.jpg"
                        },
                        new
                        {
                            Id = new Guid("cf96e6bd-ed46-440f-b7a6-74478e6c0f1c"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8200), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("c8fe1651-fd04-4c52-a3c1-634ad6d0e413"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8202), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMax4.jpg"
                        },
                        new
                        {
                            Id = new Guid("b10e0200-8dd7-4363-a910-dd8951015917"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8206), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("c8fe1651-fd04-4c52-a3c1-634ad6d0e413"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8208), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMax4.jpg"
                        },
                        new
                        {
                            Id = new Guid("8f6722d3-465d-4179-82df-45437c3616b6"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8212), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("c8fe1651-fd04-4c52-a3c1-634ad6d0e413"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8213), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMax4.jpg"
                        },
                        new
                        {
                            Id = new Guid("c46e2768-2dee-456e-b4a9-395980d959b9"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8217), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("c272683a-c8d9-4e9d-b876-16f1e6f0d557"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8218), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMaxdarkback.jpg"
                        },
                        new
                        {
                            Id = new Guid("85142851-d4db-4e6d-b79c-34f42a844c72"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8222), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("c272683a-c8d9-4e9d-b876-16f1e6f0d557"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8223), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMaxdarkback.jpg"
                        },
                        new
                        {
                            Id = new Guid("f5e85072-f168-47c5-9c9c-f49980f0c88e"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8228), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("c272683a-c8d9-4e9d-b876-16f1e6f0d557"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8229), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\iPhone13ProMaxdarkback.jpg"
                        },
                        new
                        {
                            Id = new Guid("3ea2bf49-689e-4835-afaf-0e6634bc116e"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8232), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("3384cc0b-0030-4972-9454-159d47149677"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8234), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\chris-curry-kBkD_ovDprR4-unsplash.jpg"
                        },
                        new
                        {
                            Id = new Guid("a4a74c94-afe8-4b2b-8b52-3de87ce926c3"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8238), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("3384cc0b-0030-4972-9454-159d47149677"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8239), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\chris-curry-kBkD_ovDprR4-unsplash.jpg"
                        },
                        new
                        {
                            Id = new Guid("6ba7ec7d-76ed-4e4b-a5bd-f720c829e524"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8243), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("3384cc0b-0030-4972-9454-159d47149677"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8244), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\chris-curry-kBkD_ovDprR4-unsplash.jpg"
                        },
                        new
                        {
                            Id = new Guid("ec75d4e0-6988-4e50-968b-a090b90dbaaf"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8248), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("9d9791cd-737c-4de8-bdfd-acf51a1dbb83"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8249), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\DesktopBackground.PNG"
                        },
                        new
                        {
                            Id = new Guid("30b27db0-5cfb-4191-87f2-31055a93bcf9"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8253), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("9d9791cd-737c-4de8-bdfd-acf51a1dbb83"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8254), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\DesktopBackground.PNG"
                        },
                        new
                        {
                            Id = new Guid("e055e80e-6894-43e9-bce3-3ee45c044b3e"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8259), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("9d9791cd-737c-4de8-bdfd-acf51a1dbb83"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8260), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\DesktopBackground.PNG"
                        },
                        new
                        {
                            Id = new Guid("bb16a155-3b52-4068-a639-ead927c7eb18"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8264), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("da35a95d-6862-45e1-8f10-6c0a5e1200d0"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8265), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\DesktopWallPaper.png"
                        },
                        new
                        {
                            Id = new Guid("39343150-0ebd-4034-b593-2260a85959bb"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8269), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("da35a95d-6862-45e1-8f10-6c0a5e1200d0"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8270), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\DesktopWallPaper.png"
                        },
                        new
                        {
                            Id = new Guid("23fcef43-c376-42bf-aeb9-a7814bd389b1"),
                            CreatedBy = "admin@gmail.com",
                            CreatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8274), new TimeSpan(0, 6, 0, 0, 0)),
                            ProductId = new Guid("da35a95d-6862-45e1-8f10-6c0a5e1200d0"),
                            UpdatedBy = "admin@gmail.com",
                            UpdatedDate = new DateTimeOffset(new DateTime(2022, 10, 15, 15, 53, 43, 709, DateTimeKind.Unspecified).AddTicks(8275), new TimeSpan(0, 6, 0, 0, 0)),
                            Url = "Files\\DesktopWallPaper.png"
                        });
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ReviewImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImages");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Inventory", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Product", "Product")
                        .WithOne("ProductInventory")
                        .HasForeignKey("ECommerce.Infrastructure.Entities.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.RoleClaim", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Membership.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserClaim", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Membership.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserLogin", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Membership.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserRole", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Membership.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Infrastructure.Entities.Membership.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Membership.UserToken", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Membership.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ProductCategory", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Infrastructure.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ProductImage", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Review", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.ReviewImage", b =>
                {
                    b.HasOne("ECommerce.Infrastructure.Entities.Review", "Review")
                        .WithMany("ReviewImages")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Product", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductInventory");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ECommerce.Infrastructure.Entities.Review", b =>
                {
                    b.Navigation("ReviewImages");
                });
#pragma warning restore 612, 618
        }
    }
}
