// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ECommerce.Membership.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Projects\aspnetcore-b6-intern\ec6a\ECommerce\src\ECommerce\Libraries\ECommerce.Membership\Templates\AccountConfirmationMailTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class AccountConfirmationMailTemplate : AccountConfirmationMailTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org" +
                    "/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<!-- saved from url=(0100)file:///User" +
                    "s/anisurreza/Projects/devskillv2-latest/design/pages/ds/ds-email-templates/templ" +
                    "ate.html -->\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-mi" +
                    "crosoft-com:office:office\" style=\"width:100%;font-family:arial, &#39;helvetica n" +
                    "eue&#39;, helvetica, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adju" +
                    "st:100%;padding:0;Margin:0\"><head><meta http-equiv=\"Content-Type\" content=\"text/" +
                    "html; charset=UTF-8\"> \r\n   \r\n  <meta content=\"width=device-width, initial-scale=" +
                    "1\" name=\"viewport\"> \r\n  <meta name=\"x-apple-disable-message-reformatting\"> \r\n  <" +
                    "meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> \r\n  <meta content=\"telephon" +
                    "e=no\" name=\"format-detection\"> \r\n  <title>devskill_master</title> \r\n  <!--[if (m" +
                    "so 16)]>\r\n    <style type=\"text/css\">\r\n    a {text-decoration: none;}\r\n    </sty" +
                    "le>\r\n    <![endif]--> \r\n  <!--[if gte mso 9]><style>sup { font-size: 100% !impor" +
                    "tant; }</style><![endif]--> \r\n  <!--[if gte mso 9]>\r\n<xml>\r\n    <o:OfficeDocumen" +
                    "tSettings>\r\n    <o:AllowPNG></o:AllowPNG>\r\n    <o:PixelsPerInch>96</o:PixelsPerI" +
                    "nch>\r\n    </o:OfficeDocumentSettings>\r\n</xml>\r\n<![endif]--> \r\n  <style type=\"tex" +
                    "t/css\">\r\n@media only screen and (max-width:600px) {p, ul li, ol li, a { font-siz" +
                    "e:14px!important; line-height:150%!important } h1 { font-size:24px!important; te" +
                    "xt-align:left; line-height:120%; margin-bottom:24px } h2 { font-size:20px!import" +
                    "ant; text-align:left; line-height:120%; margin-bottom:20px } h3 { font-size:16px" +
                    "!important; text-align:left; line-height:120%; margin-bottom:16px } h1 a { font-" +
                    "size:24px!important; text-align:left } h2 a { font-size:20px!important; text-ali" +
                    "gn:left } h3 a { font-size:16px!important; text-align:left } .es-menu td a { fon" +
                    "t-size:16px!important } .es-header-body p, .es-header-body ul li, .es-header-bod" +
                    "y ol li, .es-header-body a { font-size:14px!important } .es-footer-body p, .es-f" +
                    "ooter-body ul li, .es-footer-body ol li, .es-footer-body a { font-size:12px!impo" +
                    "rtant } .es-infoblock p, .es-infoblock ul li, .es-infoblock ol li, .es-infoblock" +
                    " a { font-size:12px!important } *[class=\"gmail-fix\"] { display:none!important } " +
                    ".es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3 { text-align:center!" +
                    "important } .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3 { text-a" +
                    "lign:right!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l " +
                    "h3 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l i" +
                    "mg { display:inline!important } .es-button-border { display:block!important } a." +
                    "es-button { font-size:14px!important; display:block!important; border-left-width" +
                    ":0px!important; border-right-width:0px!important } .es-btn-fw { border-width:10p" +
                    "x 0px!important; text-align:center!important } .es-adaptive table, .es-btn-fw, ." +
                    "es-btn-fw-brdr, .es-left, .es-right { width:100%!important } .es-content table, " +
                    ".es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:" +
                    "100%!important; max-width:600px!important } .es-adapt-td { display:block!importa" +
                    "nt; width:100%!important } .adapt-img { width:100%!important; height:auto!import" +
                    "ant } .es-m-p0 { padding:0px!important } .es-m-p0r { padding-right:0px!important" +
                    " } .es-m-p0l { padding-left:0px!important } .es-m-p0t { padding-top:0px!importan" +
                    "t } .es-m-p0b { padding-bottom:0!important } .es-m-p20b { padding-bottom:20px!im" +
                    "portant } .es-mobile-hidden, .es-hidden { display:none!important } tr.es-desk-hi" +
                    "dden, td.es-desk-hidden, table.es-desk-hidden { display:table-row!important; wid" +
                    "th:auto!important; overflow:visible!important; float:none!important; max-height:" +
                    "inherit!important; line-height:inherit!important } .es-desk-menu-hidden { displa" +
                    "y:table-cell!important } table.es-table-not-adapt, .esd-block-html table { width" +
                    ":auto!important } table.es-social { display:inline-block!important } table.es-so" +
                    "cial td { display:inline-block!important } .es-m-margin { padding-left:5px!impor" +
                    "tant; padding-right:5px!important; padding-top:5px!important; padding-bottom:5px" +
                    "!important } p, ul li, ol li { margin-bottom:11px!important } .es-header-body p," +
                    " .es-header-body ul li, .es-header-body ol li { margin-bottom:11px!important } ." +
                    "es-footer-body p, .es-footer-body ul li, .es-footer-body ol li { margin-bottom:9" +
                    "px!important } .es-infoblock p, .es-infoblock ul li, .es-infoblock ol li { margi" +
                    "n-bottom:9px!important } }\r\n#outlook a {\r\n\tpadding:0;\r\n}\r\n.ExternalClass {\r\n\twid" +
                    "th:100%;\r\n}\r\n.ExternalClass,\r\n.ExternalClass p,\r\n.ExternalClass span,\r\n.External" +
                    "Class font,\r\n.ExternalClass td,\r\n.ExternalClass div {\r\n\tline-height:100%;\r\n}\r\n.e" +
                    "s-button {\r\n\tmso-style-priority:100!important;\r\n\ttext-decoration:none!important;" +
                    "\r\n}\r\na[x-apple-data-detectors] {\r\n\tcolor:inherit!important;\r\n\ttext-decoration:no" +
                    "ne!important;\r\n\tfont-size:inherit!important;\r\n\tfont-family:inherit!important;\r\n\t" +
                    "font-weight:inherit!important;\r\n\tline-height:inherit!important;\r\n}\r\n.es-desk-hid" +
                    "den {\r\n\tdisplay:none;\r\n\tfloat:left;\r\n\toverflow:hidden;\r\n\twidth:0;\r\n\tmax-height:0" +
                    ";\r\n\tline-height:0;\r\n\tmso-hide:all;\r\n}\r\n.es-button-border:hover a.es-button {\r\n\tb" +
                    "ackground:#156CA6!important;\r\n\tborder-color:#156CA6!important;\r\n}\r\n.es-button-bo" +
                    "rder:hover {\r\n\tbackground:#156CA6!important;\r\n}\r\n</style> \r\n </head> \r\n <body st" +
                    "yle=\"width:100%;font-family:arial, &#39;helvetica neue&#39;, helvetica, sans-ser" +
                    "if;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0\"> " +
                    "\r\n  <div class=\"es-wrapper-color\" style=\"background-color:#F5F5FA\"> \r\n   <!--[if" +
                    " gte mso 9]>\r\n\t\t\t<v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\">" +
                    "\r\n\t\t\t\t<v:fill type=\"tile\" color=\"#F5F5FA\"></v:fill>\r\n\t\t\t</v:background>\r\n\t\t<![en" +
                    "dif]--> \r\n   <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=" +
                    "\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;bo" +
                    "rder-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:rep" +
                    "eat;background-position:center top\"> \r\n     <tbody><tr style=\"border-collapse:co" +
                    "llapse\"> \r\n      <td class=\"es-m-margin\" valign=\"top\" style=\"padding:0;Margin:0\"" +
                    "> \r\n       <table class=\"es-header\" cellspacing=\"0\" cellpadding=\"0\" align=\"cente" +
                    "r\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;bor" +
                    "der-spacing:0px;table-layout:fixed !important;width:100%;background-color:transp" +
                    "arent;background-repeat:repeat;background-position:center top\"> \r\n         <tbod" +
                    "y><tr style=\"border-collapse:collapse\"> \r\n          <td align=\"center\" style=\"pa" +
                    "dding:0;Margin:0\"> \r\n           <table class=\"es-header-body\" cellspacing=\"0\" ce" +
                    "llpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\" style=\"mso-table-lspace:0pt;mso-t" +
                    "able-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FF" +
                    "FFFF;width:600px\"> \r\n             <tbody><tr style=\"border-collapse:collapse\"> \r" +
                    "\n              <td align=\"left\" style=\"padding:0;Margin:0;padding-top:20px;paddi" +
                    "ng-left:20px;padding-right:20px\"> \r\n               <table width=\"100%\" cellspaci" +
                    "ng=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-c" +
                    "ollapse:collapse;border-spacing:0px\"> \r\n                 <tbody><tr style=\"borde" +
                    "r-collapse:collapse\"> \r\n                 </tr> \r\n               </tbody></table>" +
                    "</td> \r\n             </tr> \r\n           </tbody></table></td> \r\n         </tr> \r" +
                    "\n       </tbody></table> \r\n       <table class=\"es-content\" cellspacing=\"0\" cell" +
                    "padding=\"0\" align=\"center\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;bord" +
                    "er-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%" +
                    "\"> \r\n         <tbody><tr style=\"border-collapse:collapse\"> \r\n          <td align" +
                    "=\"center\" style=\"padding:0;Margin:0\"> \r\n           <table class=\"es-content-body" +
                    "\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\" style=\"mso-ta" +
                    "ble-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;" +
                    "background-color:#FFFFFF;width:600px\"> \r\n             <tbody><tr style=\"border-c" +
                    "ollapse:collapse\"> \r\n              <td align=\"left\" style=\"Margin:0;padding-top:" +
                    "20px;padding-bottom:20px;padding-left:20px;padding-right:20px\"> \r\n              " +
                    " <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt" +
                    ";mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\"> \r\n          " +
                    "       <tbody><tr style=\"border-collapse:collapse\"> \r\n                  <td vali" +
                    "gn=\"top\" align=\"center\" style=\"padding:0;Margin:0;width:560px\"> \r\n              " +
                    "     <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\" sty" +
                    "le=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-sp" +
                    "acing:0px\"> \r\n                     <tbody><tr style=\"border-collapse:collapse\"> " +
                    "\r\n                     <tr style=\"border-collapse:collapse\"> \r\n                 " +
                    "     <td align=\"left\" style=\"padding:0;Margin:0\"><p style=\"Margin:0;-webkit-text" +
                    "-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-si" +
                    "ze:14px;font-family:arial, &#39;helvetica neue&#39;, helvetica, sans-serif;line-" +
                    "height:21px;margin-bottom:15px;color:#051B29\"> Thanks for registering for an acc" +
                    "ount on ECommerce. Before we get started, we just need to confirm that this is y" +
                    "ou. verify your email address.</p>\r\n                     </tr> \r\n               " +
                    "       <tr style=\"border-collapse:collapse\"> \r\n                      <td align=\"" +
                    "left\" style=\"padding:0;Margin:0;padding-right:10px;padding-top:20px;padding-bott" +
                    "om:30px\"><span class=\"es-button-border\" style=\"border-style:solid;border-color:#" +
                    "2CB543;background:#197FC3;border-width:0px;display:inline-block;border-radius:4p" +
                    "x;width:auto\"><a href=\"");
            
            #line 114 "C:\Projects\aspnetcore-b6-intern\ec6a\ECommerce\src\ECommerce\Libraries\ECommerce.Membership\Templates\AccountConfirmationMailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(VerificationLink));
            
            #line default
            #line hidden
            this.Write(@""" class=""es-button"" target=""_blank"" style=""mso-style-priority:100 !important;text-decoration:none;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, &#39;helvetica neue&#39;, helvetica, sans-serif;font-size:14px;color:#FFFFFF;border-style:solid;border-color:#197FC3;border-width:10px 20px;display:inline-block;background:#197FC3;border-radius:4px;font-weight:normal;font-style:normal;line-height:17px;width:auto;text-align:center"">Click Here</a></span></td> 
                     </tr>
<tr style=""border-collapse:collapse""> 
                      <td style=""padding:20px;Margin:0;font-size:0"" align=""center""> 
                       <table width=""100%"" height=""100%"" cellspacing=""0"" cellpadding=""0"" border=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""> 
                         <tbody><tr style=""border-collapse:collapse""> 
                          <td style=""padding:0;Margin:0px;border-bottom:1px solid #E7E6F0;height:1px;width:100%;margin:0px""></td> 
                         </tr> 
                       </tbody></table></td>
                   </tbody></table></td> 
                 </tr> 
               </tbody></table></td> 
             </tr> 
           </tbody></table></td> 
         </tr> 
       </tbody></table> 
       </td> 
         </tr> 
       </tbody></table></td> 
     </tr> 
   </tbody></table> 
  </div>  
</body></html>
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class AccountConfirmationMailTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
