name: ECommerce Build
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checking out Code
      uses: actions/checkout@v2
    - name: Installing .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restoring Packages
      run: dotnet restore "src/ECommerce/ECommerce.sln"
    - name: Building Project(s)
      run: dotnet build "src/ECommerce/ECommerce.sln" --no-restore
    - name: Running Tests
      run: dotnet test "src/ECommerce/ECommerce.sln" --no-build --verbosity normal
